name: Publish Nuget Package

on:
  push:
    tags:
      - '*.*.**'
     
jobs:
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          sed -i -e 's/0.0.0/${{ github.ref_name }}/' ./lib/Identity.Marten/Identity.Marten.csproj
      - name: Pack
        run: |
          dotnet pack ./lib/Identity.Marten -c Release -o .output
      - name: Publish
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
    